// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const directUrl =
  process.env.DIRECT_URL ??
  process.env.DATABASE_URL_UNPOOLED ??
  process.env.POSTGRES_URL_NON_POOLING;

const databaseUrl =
  process.env.DATABASE_URL ??
  process.env.POSTGRES_PRISMA_URL ??
  process.env.POSTGRES_URL;

const prismaDatasourceUrl = directUrl ?? databaseUrl;

if (!prismaDatasourceUrl) {
  throw new Error(
    "Prisma requires one of DIRECT_URL, DATABASE_URL_UNPOOLED, POSTGRES_URL_NON_POOLING, DATABASE_URL, POSTGRES_PRISMA_URL, or POSTGRES_URL.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node ./prisma/seed.ts",
  },
  datasource: {
    url: prismaDatasourceUrl,
  },
});
