export const COUNTRY_OPTIONS = [
  "Argentina",
  "Australia",
  "Austria",
  "Barbados",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Egypt",
  "England",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Guyana",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Kenya",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Northern Ireland",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Scotland",
  "Singapore",
  "Slovakia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "United States",
  "Uruguay",
  "Vietnam",
  "Wales",
] as const;

const COUNTRY_TO_CODE: Record<string, string> = {
  canada: "CA",
  "united states": "US",
  usa: "US",
  us: "US",
  mexico: "MX",
  jamaica: "JM",
  trinidad: "TT",
  "trinidad and tobago": "TT",
  guyana: "GY",
  barbados: "BB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  "united kingdom": "GB",
  uk: "GB",
  ireland: "IE",
  "northern ireland": "GB",
  france: "FR",
  germany: "DE",
  italy: "IT",
  spain: "ES",
  portugal: "PT",
  netherlands: "NL",
  belgium: "BE",
  switzerland: "CH",
  austria: "AT",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  poland: "PL",
  czechia: "CZ",
  "czech republic": "CZ",
  slovakia: "SK",
  hungary: "HU",
  romania: "RO",
  bulgaria: "BG",
  greece: "GR",
  turkey: "TR",
  cyprus: "CY",
  india: "IN",
  pakistan: "PK",
  china: "CN",
  japan: "JP",
  "south korea": "KR",
  korea: "KR",
  taiwan: "TW",
  thailand: "TH",
  vietnam: "VN",
  philippines: "PH",
  malaysia: "MY",
  singapore: "SG",
  indonesia: "ID",
  australia: "AU",
  "new zealand": "NZ",
  egypt: "EG",
  morocco: "MA",
  tunisia: "TN",
  "south africa": "ZA",
  nigeria: "NG",
  kenya: "KE",
  brazil: "BR",
  argentina: "AR",
  chile: "CL",
  colombia: "CO",
  peru: "PE",
  uruguay: "UY",
};

export function normalizeCountryCode(country: string | null | undefined) {
  const normalized = country?.trim() ?? "";

  if (!normalized) return "";

  if (/^[a-zA-Z]{2}$/.test(normalized)) {
    return normalized.toUpperCase();
  }

  return COUNTRY_TO_CODE[normalized.toLowerCase()] || "";
}

export function getFlagCdnUrl(country: string | null | undefined, size: "w20" | "w40" | "w80" = "w40") {
  const countryCode = normalizeCountryCode(country);
  return countryCode ? `https://flagcdn.com/${size}/${countryCode.toLowerCase()}.png` : null;
}